// lib/production/mock-data.ts

import type { ProductionOrder, ProductionAlert } from '@/types/production'

const now = new Date()
const hoursFromNow = (h: number) =>
  new Date(now.getTime() + h * 3600000).toISOString()
const hoursAgo = (h: number) =>
  new Date(now.getTime() - h * 3600000).toISOString()

export const MOCK_PRODUCTION_ORDERS: ProductionOrder[] = [

  // ORDER 1 — Critical, in production, behind pace (UNDP 2000 t-shirts)
  {
    id: 'prod-001',
    orderNo: 'PO-2026-0047',
    clientOrderRef: 'KIN-2025-0055',
    clientName: 'UNDP',
    company: 'Kingsport',
    receivedBy: 'Thandeka Madeya',
    signedOffBy: 'Kingstone Mhako',
    signedOffAt: hoursAgo(6),
    orderReceivedAt: hoursAgo(7),
    deadlineAt: hoursFromNow(18),
    urgencyLevel: 'critical',
    overnightShiftRequired: false,
    status: 'in_production',
    riskStatus: 'critical',
    riskReason: 'Printing pace at 78% of required rate. Projected to finish 3.2 hours late at current pace.',
    allFabricConfirmed: true,
    linkedPurchaseOrderIds: [],
    notes: 'UNDP Zimbabwe Youth Conference shirts. Client will collect.',
    internalNotes: 'Check print registration carefully — 4 colour process.',
    subJobs: [
      {
        id: 'sj-001',
        productionOrderId: 'prod-001',
        subJobNo: 'SJ-001',
        productType: 'T-Shirt',
        colour: 'White',
        totalQuantity: 2000,
        sizeBreakdown: { S: 300, M: 600, L: 700, XL: 300, XXL: 100 },
        hasPrinting: true,
        printDescription: 'Full front graphic — UNDP branding + conference theme, 4 colour process',
        printColourCount: 4,
        hasEmbroidery: false,
        styleNotes: 'Round neck, standard weight 160gsm',
        complexityRating: 'complex',
        fabricType: 'Interlock 80/20',
        fabricColour: 'White',
        fabricQuantityMetres: 480,
        fabricStatus: 'in_stock',
        sewingRequired: true,
        sewingStarted: true,
        sewingCompleted: false,
        sewingPiecesCompleted: 420,
        printingRequired: true,
        printingStarted: true,
        printingCompleted: false,
        printingPiecesCompleted: 280,
        finishingStarted: true,
        finishingCompleted: false,
        finishingPiecesCompleted: 180,
        status: 'in_progress',
        pieceCountTrackingEnabled: true,
        stages: [
          {
            stageName: 'cutting',
            status: 'completed',
            startedAt: hoursAgo(5.5),
            completedAt: hoursAgo(4),
            startedBy: 'Energy Deshe',
            completedBy: 'Energy Deshe',
            piecesIn: 2000,
            piecesOut: 2000,
          },
          {
            stageName: 'sewing',
            status: 'in_progress',
            startedAt: hoursAgo(3.8),
            startedBy: 'Sewing Supervisor',
            piecesIn: 2000,
          },
          {
            stageName: 'printing',
            status: 'in_progress',
            startedAt: hoursAgo(3.5),
            startedBy: 'Printing Supervisor',
            piecesIn: 2000,
            notes: 'Graphic design finalised at 10:30. 4-colour screen setup complete.',
          },
          { stageName: 'finishing', status: 'in_progress', startedAt: hoursAgo(1) },
          { stageName: 'quality_check', status: 'pending' },
          { stageName: 'packaging', status: 'pending' },
          { stageName: 'dispatch', status: 'pending' },
        ],
      },
    ],
  },

  // ORDER 2 — Urgent, fabric being sourced (Natpharm — split order)
  {
    id: 'prod-002',
    orderNo: 'PO-2026-0046',
    clientOrderRef: 'KIN-2025-0049',
    clientName: 'Natpharm',
    company: 'Kingsport',
    receivedBy: 'Spiwe Mandizha',
    signedOffBy: 'Blessing Mhako',
    signedOffAt: hoursAgo(3),
    orderReceivedAt: hoursAgo(4),
    deadlineAt: hoursFromNow(36),
    urgencyLevel: 'urgent',
    status: 'fabric_sourcing',
    riskStatus: 'at_risk',
    riskReason: 'Navy fabric for golf shirts being sourced. Cutting cannot begin until delivery confirmed.',
    allFabricConfirmed: false,
    linkedPurchaseOrderIds: ['FABPO-001'],
    notes: 'Natpharm staff uniform order. Deliver to Natpharm depot, Msasa.',
    internalNotes: 'Navy interlock not in stock — Apex Textiles PO raised.',
    subJobs: [
      {
        id: 'sj-002',
        productionOrderId: 'prod-002',
        subJobNo: 'SJ-001',
        productType: 'Golf Shirt',
        colour: 'Navy',
        totalQuantity: 500,
        sizeBreakdown: { S: 50, M: 150, L: 200, XL: 80, XXL: 20 },
        hasPrinting: true,
        printDescription: 'Left chest embroidered Natpharm logo',
        printColourCount: 2,
        hasEmbroidery: true,
        complexityRating: 'standard',
        fabricType: 'Pique Knit',
        fabricColour: 'Navy',
        fabricQuantityMetres: 165,
        fabricStatus: 'sourcing',
        fabricLinkedPOId: 'FABPO-001',
        sewingRequired: true,
        sewingStarted: false,
        sewingCompleted: false,
        sewingPiecesCompleted: 0,
        printingRequired: true,
        printingStarted: false,
        printingCompleted: false,
        printingPiecesCompleted: 0,
        finishingStarted: false,
        finishingCompleted: false,
        finishingPiecesCompleted: 0,
        status: 'queued',
        pieceCountTrackingEnabled: true,
        stages: [
          { stageName: 'cutting', status: 'pending' },
          { stageName: 'sewing', status: 'pending' },
          { stageName: 'printing', status: 'pending' },
          { stageName: 'finishing', status: 'pending' },
          { stageName: 'quality_check', status: 'pending' },
          { stageName: 'packaging', status: 'pending' },
          { stageName: 'dispatch', status: 'pending' },
        ],
      },
      {
        id: 'sj-003',
        productionOrderId: 'prod-002',
        subJobNo: 'SJ-002',
        productType: 'T-Shirt',
        colour: 'White',
        totalQuantity: 300,
        sizeBreakdown: { S: 60, M: 100, L: 100, XL: 40 },
        hasPrinting: true,
        printDescription: 'Left chest Natpharm logo, 2 colours',
        printColourCount: 2,
        complexityRating: 'simple',
        fabricType: 'Interlock 160gsm',
        fabricColour: 'White',
        fabricQuantityMetres: 72,
        fabricStatus: 'in_stock',
        sewingRequired: true,
        sewingStarted: false,
        sewingCompleted: false,
        sewingPiecesCompleted: 0,
        printingRequired: true,
        printingStarted: false,
        printingCompleted: false,
        printingPiecesCompleted: 0,
        finishingStarted: false,
        finishingCompleted: false,
        finishingPiecesCompleted: 0,
        status: 'queued',
        pieceCountTrackingEnabled: false,
        stages: [
          { stageName: 'cutting', status: 'pending' },
          { stageName: 'sewing', status: 'pending' },
          { stageName: 'printing', status: 'pending' },
          { stageName: 'finishing', status: 'pending' },
          { stageName: 'quality_check', status: 'pending' },
          { stageName: 'packaging', status: 'pending' },
          { stageName: 'dispatch', status: 'pending' },
        ],
      },
    ],
  },

  // ORDER 3 — Standard, on track, in finishing (PSC polo shirts)
  {
    id: 'prod-003',
    orderNo: 'PO-2026-0045',
    clientOrderRef: 'KIN-2025-0038',
    clientName: 'PSC',
    company: 'Kingsport',
    receivedBy: 'Lucia Chiwanza',
    signedOffBy: 'Energy Deshe',
    signedOffAt: hoursAgo(48),
    orderReceivedAt: hoursAgo(50),
    deadlineAt: hoursFromNow(72),
    urgencyLevel: 'standard',
    status: 'in_production',
    riskStatus: 'on_track',
    allFabricConfirmed: true,
    linkedPurchaseOrderIds: [],
    notes: 'PSC management polo shirts. Standard order.',
    internalNotes: '',
    subJobs: [
      {
        id: 'sj-004',
        productionOrderId: 'prod-003',
        subJobNo: 'SJ-001',
        productType: 'Polo Shirt',
        colour: 'Sky Blue',
        totalQuantity: 150,
        sizeBreakdown: { M: 50, L: 60, XL: 30, XXL: 10 },
        hasPrinting: true,
        printDescription: 'Left chest PSC crest, 1 colour',
        printColourCount: 1,
        complexityRating: 'standard',
        fabricType: 'Pique Knit 180gsm',
        fabricColour: 'Sky Blue',
        fabricQuantityMetres: 52,
        fabricStatus: 'in_stock',
        sewingRequired: true,
        sewingStarted: true,
        sewingCompleted: true,
        sewingPiecesCompleted: 150,
        printingRequired: true,
        printingStarted: true,
        printingCompleted: true,
        printingPiecesCompleted: 150,
        finishingStarted: true,
        finishingCompleted: false,
        finishingPiecesCompleted: 80,
        status: 'finishing',
        pieceCountTrackingEnabled: false,
        stages: [
          {
            stageName: 'cutting',
            status: 'completed',
            startedAt: hoursAgo(46),
            completedAt: hoursAgo(44),
            startedBy: 'Energy Deshe',
            completedBy: 'Energy Deshe',
            piecesIn: 150,
            piecesOut: 150,
          },
          {
            stageName: 'sewing',
            status: 'completed',
            startedAt: hoursAgo(43),
            completedAt: hoursAgo(36),
            startedBy: 'Sewing Supervisor',
            completedBy: 'Sewing Supervisor',
            piecesIn: 150,
            piecesOut: 150,
          },
          {
            stageName: 'printing',
            status: 'completed',
            startedAt: hoursAgo(38),
            completedAt: hoursAgo(30),
            startedBy: 'Printing Supervisor',
            completedBy: 'Printing Supervisor',
            piecesIn: 150,
            piecesOut: 150,
          },
          {
            stageName: 'finishing',
            status: 'in_progress',
            startedAt: hoursAgo(8),
            startedBy: 'Finishing Supervisor',
            piecesIn: 150,
          },
          { stageName: 'quality_check', status: 'pending' },
          { stageName: 'packaging', status: 'pending' },
          { stageName: 'dispatch', status: 'pending' },
        ],
      },
    ],
  },

  // ORDER 4 — Urgent, pending sign-off (Ministry of Health — just received)
  {
    id: 'prod-004',
    orderNo: 'PO-2026-0048',
    clientOrderRef: 'KIN-2025-0060',
    clientName: 'Ministry of Health',
    company: 'Kingsport',
    receivedBy: 'Thandeka Madeya',
    orderReceivedAt: hoursAgo(0.5),
    deadlineAt: hoursFromNow(30),
    urgencyLevel: 'urgent',
    status: 'pending_signoff',
    riskStatus: 'on_track',
    allFabricConfirmed: false,
    linkedPurchaseOrderIds: [],
    notes: 'MoH community health worker vests. Urgent — national campaign.',
    internalNotes: '',
    subJobs: [
      {
        id: 'sj-005',
        productionOrderId: 'prod-004',
        subJobNo: 'SJ-001',
        productType: 'Vest',
        colour: 'Yellow',
        totalQuantity: 800,
        sizeBreakdown: { S: 100, M: 300, L: 300, XL: 100 },
        hasPrinting: true,
        printDescription: 'Full front Ministry of Health logo + Zimbabwe crest, 3 colours',
        printColourCount: 3,
        complexityRating: 'complex',
        fabricType: 'Woven Polyester',
        fabricColour: 'Yellow',
        fabricQuantityMetres: 280,
        fabricStatus: 'not_assessed',
        sewingRequired: true,
        sewingStarted: false,
        sewingCompleted: false,
        sewingPiecesCompleted: 0,
        printingRequired: true,
        printingStarted: false,
        printingCompleted: false,
        printingPiecesCompleted: 0,
        finishingStarted: false,
        finishingCompleted: false,
        finishingPiecesCompleted: 0,
        status: 'queued',
        pieceCountTrackingEnabled: true,
        stages: [
          { stageName: 'cutting', status: 'pending' },
          { stageName: 'sewing', status: 'pending' },
          { stageName: 'printing', status: 'pending' },
          { stageName: 'finishing', status: 'pending' },
          { stageName: 'quality_check', status: 'pending' },
          { stageName: 'packaging', status: 'pending' },
          { stageName: 'dispatch', status: 'pending' },
        ],
      },
    ],
  },
]

// Mock alerts — pre-seeded for development
export const MOCK_PRODUCTION_ALERTS: ProductionAlert[] = [
  {
    id: 'alert-001',
    productionOrderId: 'prod-001',
    subJobId: 'sj-001',
    alertType: 'order_behind_pace',
    severity: 'critical',
    message: 'Order behind pace — PO-2026-0047 (UNDP): T-Shirt needs 95 pieces/hour to meet deadline but is achieving 74 pieces/hour. At current pace, delivery will be 3.2 hours late. Deadline: 18 hours from now.',
    raisedAt: hoursAgo(0.5),
    resolved: false,
  },
  {
    id: 'alert-002',
    productionOrderId: 'prod-002',
    subJobId: 'sj-002',
    alertType: 'fabric_not_confirmed',
    severity: 'warning',
    message: 'Fabric not assessed — PO-2026-0046 (Natpharm) Navy Pique Knit is being sourced. Cutting blocked until fabric delivery confirmed.',
    raisedAt: hoursAgo(2),
    resolved: false,
  },
]

// Mock fabric purchase orders
export const MOCK_FABRIC_POS = [
  {
    id: 'FABPO-001',
    productionOrderId: 'prod-002',
    subJobId: 'sj-002',
    supplier: 'Apex Textiles',
    item: 'Pique Knit · Navy',
    quantityMetres: 165,
    unitPrice: 4.5,
    totalAmount: 742.5,
    currency: 'USD' as const,
    paymentMethod: 'Bank Transfer' as const,
    expectedDeliveryAt: hoursFromNow(8),
    status: 'raised' as const,
    notes: 'Standard navy interlock — confirm shade matches previous batch',
  },
]

// Activity log entries (mock)
export const MOCK_ACTIVITY_LOG: Array<{
  id: string
  productionOrderId: string
  timestamp: string
  userName: string
  action: string
}> = [
  { id: 'log-001', productionOrderId: 'prod-001', timestamp: hoursAgo(7), userName: 'Thandeka Madeya', action: 'Order received and created — PO-2026-0047 (UNDP · 2,000 pcs)' },
  { id: 'log-002', productionOrderId: 'prod-001', timestamp: hoursAgo(6.5), userName: 'Kingstone Mhako', action: 'Order signed off — fabric assessment and cutting timers started' },
  { id: 'log-003', productionOrderId: 'prod-001', timestamp: hoursAgo(6), userName: 'Energy Deshe', action: 'Fabric confirmed in stock — 480m Interlock 80/20 White' },
  { id: 'log-004', productionOrderId: 'prod-001', timestamp: hoursAgo(5.5), userName: 'Energy Deshe', action: 'Cutting started — 2,000 panels' },
  { id: 'log-005', productionOrderId: 'prod-001', timestamp: hoursAgo(4), userName: 'Energy Deshe', action: 'Cutting completed — 2,000 panels out' },
  { id: 'log-006', productionOrderId: 'prod-001', timestamp: hoursAgo(3.8), userName: 'Sewing Supervisor', action: 'Sewing started' },
  { id: 'log-007', productionOrderId: 'prod-001', timestamp: hoursAgo(3.5), userName: 'Printing Supervisor', action: 'Printing started — graphic design finalised, 4-colour screens set up' },
  { id: 'log-008', productionOrderId: 'prod-001', timestamp: hoursAgo(2), userName: 'Sewing Supervisor', action: 'Piece count updated — 420 pieces sewn' },
  { id: 'log-009', productionOrderId: 'prod-001', timestamp: hoursAgo(1.5), userName: 'Printing Supervisor', action: 'Piece count updated — 280 pieces printed' },
  { id: 'log-010', productionOrderId: 'prod-001', timestamp: hoursAgo(1), userName: 'Finishing Supervisor', action: 'Finishing started — 180 pieces ready for finishing' },
  { id: 'log-011', productionOrderId: 'prod-001', timestamp: hoursAgo(0.5), userName: 'System', action: '🔴 Alert raised: Order behind pace. Printing at 74pcs/hr, needs 95pcs/hr to meet deadline.' },
]
